#!/bin/bash
MailId="mogalidevops@gmail.com"
echo -e "The file system utilization is $(hostname -s) is: \n $(df -H | grep -E "/dev/root" | awk '{print  $5}')" | /usr/bin/mail -s "filesystem utilization" "$MailId"

